<?php include '../config.php'?>
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <?php include '../Headercssin.php'?>
  <title>Offer Letter</title>
</head>

<body>
  <!-- <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script> -->
  <!-- <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script> -->

  <div class="dashboard-main-wrapper">

    <?php include '../headerin.php'?>
    <?php include '../Sidebarin.php'?>
    <div class="dashboard-wrapper">

      <div class="row">
        <div class="col-lg-9">


          <div class="card" style="margin: 30px">
            <h5 class="card-header text-green">Offer Letter</h5>


              <a id="data_to_image_btn" class="btn btn-info btn-nda-down"><i class="fa fa-download"></i>
                Download</a>
            <div class="card-body">

              <div id="pdfExport" >

                <div class="pdf-sipl">
                <div class="pdf-header-sipl"> <img src="../Logo/Sainmarknewlogo.png" width="130" height="50" />
                <p><b>Sainmarks Industries (India) Pvt Ltd</b><br/>
                476/1b/1a, Label Arcade, Jothi Nagar, Palavanjipalayam,<br/>
               Dharapuram Main Road, Tirupur-641 608.</p></div>
              <hr/>
              
<style>
  .btn-nda-down{
    position: absolute;
    top: 5px;
    right:15px;
  }
p{
  text-align: justify;
}
.div-table {
 display: table;     
 width: 100%;     
}
.div-table-row {
 display: table-row;
 width: 100%;
 clear: both;
}
.div-table-col {
 float: left; /* fix for buggy browsers */
  width: 50%;
 display: table-column;     
}
h4{
  text-align: center;font-weight: bold;
}
.nda-ta-content p, .nda-ta-content ul li{
font-size: 15px;
}
.nda-ta-content p u{font-weight: bold;}

</style>


<div class='nda-ta-content'><br/>

<h4>Offer Letter</h4>
  
  <div class="row">
    <div class="col-md-6"><p><b>To,</b><br/><br/><br/><br/><br/><br/></p></div><div class="col-md-6 text-right"><b>Date: 00-00-0000</b></div></div>

<p>Sub: – Offer Letter</p>

<p class="text-bold">Dear……………………., </p>

<p>Subsequent to your successful interview with BRITANNIA LABELS INDIA PVT LTD, TIRUPUR. We are pleased to offer you the position as “…………………..” in our organization. We take pleasure to inform you that your CTC will be ………………….</p>

<p>Our bonus policy is as per act 8.33% on BASIC + DA after completion of 30 days attendance. There is any law stating that in case an employee is absent without an approved leave for more than 10 days that can be treated as their voluntary resignation.</p>

<p>You are requested to join us on ……………………... </p>


<p class="text-bold">You are requested to carry the below-mentioned documents at the time of joining:</p>
<div class="ml-5">
<p>1. Aadhar Card.</p>

<p>2. All Educational certificates (photocopies).</p>

<p>3. Passport size photographs x 4 copies.</p>

<p>4. Documents of proof of residence (Permanent & Current).</p>

<p>5. Pan Card.</p>

<p>6. Savings account passbook.</p>

<p>7. Vaccination Certificate.</p>
</div>
<p>The formal letter of appointment containing details of the terms and conditions of the employment will be issued to you after your joining with us. Please sign and return the duplicate copy of this letter as a token of your acceptance to this offer.</p>

<br/>
<p class="text-bold">Yours truly,</p>
<br/><br/>
<p class="text-bold">General Manager</p>

                
                

              </div>




              
    



                </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>


  <?php include '../footer.php'?>
  </div>



  </div>

  <?php include '../footerjs.php'?>
  <script src="../Scripts/jspdf.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script> -->
  <script src="../assets/libs/js/html2canvas.min.js"></script>
  <!-- <script>
  $(function() {
    $("#data_to_image_btn").click(function() {

      var HTML_Width = $("#pdfExport").width();
      var HTML_Height = $("#pdfExport").height();
      var data = document.getElementById('pdfExport');
      html2canvas(data,{ allowTaint: true, scale :3,useCORS : true }).then(canvas => {
       

        var contentWidth = canvas.width;
   var contentHeight = canvas.height;
   //One page pdf shows the canvas height generated by html pages.
   var pageHeight = contentWidth / 592.28 * 841.89;
   //html page height without pdf generation
   var leftHeight = contentHeight;
   //Page offset
   var position = 2;
   //a4 paper size [595.28, 841.89], html page generated canvas in pdf picture width
   var imgWidth = 595.28;
   var imgHeight = 592.28/contentWidth * contentHeight;
   var pageData = canvas.toDataURL('image/jpeg', 1.0);
   var pdf = new jsPDF('', 'pt', 'a4');
   //There are two heights to distinguish, one is the actual height of the html page, and the page height of the generated pdf (841.89)
   //When the content does not exceed the range of pdf page display, there is no need to paginate
   if (leftHeight < pageHeight) {
   pdf.addImage(pageData, 'JPEG', 2, 2, imgWidth, imgHeight );
   } else {
     while(leftHeight > 0) {
       pdf.addImage(pageData, 'jpg', 2, position, imgWidth, imgHeight)
       leftHeight -= pageHeight;
       position -= 841.89;
       //Avoid adding blank pages
       if(leftHeight > 0) {
        pdf.addPage();
       }
     }
   }
   // pdf.save('content.pdf');


   window.open(pdf.output('bloburl', {
          filename: 'new-file.pdf'
        }), '_blank');
      });

    });
  });



  function demoFromHTML() {
    var data = document.getElementById('pdfExport');
    html2canvas(data, {
      onrendered: function(canvasObj) {
        var contentWidth = canvas.width;
   var contentHeight = canvas.height;
   //One page pdf shows the canvas height generated by html pages.
   var pageHeight = contentWidth / 592.28 * 841.89;
   //html page height without pdf generation
   var leftHeight = contentHeight;
   //Page offset
   var position = 0;
   //a4 paper size [595.28, 841.89], html page generated canvas in pdf picture width
   var imgWidth = 595.28;
   var imgHeight = 592.28/contentWidth * contentHeight;
   var pageData = canvas.toDataURL('image/jpeg', 1.0);
   var pdf = new jsPDF('', 'pt', 'a4');
   //There are two heights to distinguish, one is the actual height of the html page, and the page height of the generated pdf (841.89)
   //When the content does not exceed the range of pdf page display, there is no need to paginate
   if (leftHeight < pageHeight) {
   pdf.addImage(pageData, 'JPEG', 0, 0, imgWidth, imgHeight );
   } else {
     while(leftHeight > 0) {
       pdf.addImage(pageData, 'JPEG', 0, position, imgWidth, imgHeight)
       leftHeight -= pageHeight;
       position -= 841.89;
       //Avoid adding blank pages
       if(leftHeight > 0) {
        pdf.addPage();
       }
     }
   }
   pdf.save('content.pdf');
      }
    });
  }
  </script> -->






</body>

</html>























