<?php 

include('../config.php');
include('../session.php');

?><!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <?php include '../Headercssin.php'?>
    <title>FORM NO.34 - Nomination</title>
</head>

<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">

        <?php include '../headerin.php'?>
        <?php include '../Sidebarin.php'?>
        <div class="dashboard-wrapper" >
            <div class="container-fluid">
    

            <div class="pdf-data" style="margin: 30px">
                        <h5 class="card-header text-green">FORM NO.34 - Nomination</h5>

            <a id="data_to_image_btn" class="btn btn-info btn-nda-down"><i class="fa fa-download"></i>
                                Download</a>
             <div id="pdfExport">

         <div class="pdf-sipl">
              <div class="pdf-header-sipl"> <img src="../Logo/Sainmarknewlogo.png" width="130"
                    height="50" />


            
        <p><b>Sainmarks Industries (India) Pvt Ltd</b><br />
            476/1b/1a, Label Arcade, Jothi Nagar, Palavanjipalayam,<br />
            Dharapuram Main Road, Tirupur-641 608.</p>
    </div>
    <hr />


   
                               
                                
<p style="text-align:left;">To <br/>பெறுதல்<span style="float:right;">DATE : 00-00-0000</span></p>
<br/><br/><br/><br/><br/><br/>
<div><p>&emsp;&emsp;&emsp;&emsp;&emsp;உங்களது பணி நியமன உத்தரவு __________ தேதியிட்ட கடிதத்தை தொடர்ந்து உங்களது திறமையின் அடிப்படையிலும் உங்களின் நன்நடத்தை, செயல்பாடுகளின் அடிப்படையிலும் உங்களை எமது நிர்வாகம் ____________முதல் பணி நிரந்தரம் செய்வதில் பெருமிதம் கொள்கிறது. ங்களது சம்பளம் கீழ்க்கண்டவாறு நிர்ணயிக்கபடுகிறது.</p>
<p>&emsp;&emsp;&emsp;&emsp;&emsp;சம்பளம் ரூ. _______________ நாள் / மாதம் மேலும் பிடித்தங்களிலும் ஏனைய விதிமுறைகளிலும் எந்தவித மாற்றமும் இல்லை. எனவே தொடந்து உமது பணியை செவ்வனே செய்து நிர்வாகத்தின் வளர்ச்சியும் தங்களின் வளர்ச்சியும் மேம்பட வாழ்த்துகளை தெரிவித்து கொள்கிறது.</p>
</div>
<p>இப்படிக்கு,</p>



<p style="text-align:left;">உண்மைநகல் பெற்றுக்கொண்டேன்<span style="float:right;">நிர்வாகம் /அங்கீகாரம் பெற்ற அதிகாரி</span></p>



                            </div>




                           
        



                                </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


    <?php include '../footer.php'?>
    </div>



    </div>

    <?php include '../footerjs.php'?>
    <script src="../Scripts/jspdf.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script> -->
    <script src="../assets/libs/js/html2canvas.min.js"></script>
    <script>
    $(function() {
        $("#data_to_image_btn").click(function() {

            var HTML_Width = $("#pdfExport").width();
            var HTML_Height = $("#pdfExport").height();
            var data = document.getElementById('pdfExport');
            html2canvas(data,{ allowTaint: true, scale :3,useCORS : true }).then(canvas => {
             

                var contentWidth = canvas.width;
      var contentHeight = canvas.height;
      //One page pdf shows the canvas height generated by html pages.
      var pageHeight = contentWidth / 592.28 * 841.89;
      //html page height without pdf generation
      var leftHeight = contentHeight;
      //Page offset
      var position = 2;
      //a4 paper size [595.28, 841.89], html page generated canvas in pdf picture width
      var imgWidth = 595.28;
      var imgHeight = 592.28/contentWidth * contentHeight;
      var pageData = canvas.toDataURL('image/jpeg', 1.0);
      var pdf = new jsPDF('', 'pt', 'a4');
      //There are two heights to distinguish, one is the actual height of the html page, and the page height of the generated pdf (841.89)
      //When the content does not exceed the range of pdf page display, there is no need to paginate
      if (leftHeight < pageHeight) {
      pdf.addImage(pageData, 'JPEG', 2, 2, imgWidth, imgHeight );
      } else {
          while(leftHeight > 0) {
              pdf.addImage(pageData, 'jpg', 2, position, imgWidth, imgHeight)
              leftHeight -= pageHeight;
              position -= 841.89;
              //Avoid adding blank pages
              if(leftHeight > 0) {
                pdf.addPage();
              }
          }
      }
     // pdf.save('content.pdf');


      window.open(pdf.output('bloburl', {
                    filename: 'new-file.pdf'
                }), '_blank');
            });

        });
    });



    function demoFromHTML() {
        var data = document.getElementById('pdfExport');
        html2canvas(data, {
            onrendered: function(canvasObj) {
                var contentWidth = canvas.width;
      var contentHeight = canvas.height;
      //One page pdf shows the canvas height generated by html pages.
      var pageHeight = contentWidth / 592.28 * 841.89;
      //html page height without pdf generation
      var leftHeight = contentHeight;
      //Page offset
      var position = 0;
      //a4 paper size [595.28, 841.89], html page generated canvas in pdf picture width
      var imgWidth = 595.28;
      var imgHeight = 592.28/contentWidth * contentHeight;
      var pageData = canvas.toDataURL('image/jpeg', 1.0);
      var pdf = new jsPDF('', 'pt', 'a4');
      //There are two heights to distinguish, one is the actual height of the html page, and the page height of the generated pdf (841.89)
      //When the content does not exceed the range of pdf page display, there is no need to paginate
      if (leftHeight < pageHeight) {
      pdf.addImage(pageData, 'JPEG', 0, 0, imgWidth, imgHeight );
      } else {
          while(leftHeight > 0) {
              pdf.addImage(pageData, 'JPEG', 0, position, imgWidth, imgHeight)
              leftHeight -= pageHeight;
              position -= 841.89;
              //Avoid adding blank pages
              if(leftHeight > 0) {
                pdf.addPage();
              }
          }
      }
      pdf.save('content.pdf');
            }
        });
    }
    </script>





    <!-- //<script src="../Scripts/Controller/NDAtamilController.js"></script> -->

</body>

</html>























