<?php
include('../config.php');
include('../session.php');
?>
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <?php include '../Headercssin.php'?>
    <title>FORM NO.34 - Nomination</title>
</head>

<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">

        <?php include '../headerin.php'?>
        <?php include '../Sidebarin.php'?>
        <div class="dashboard-wrapper" >
            <div class="container-fluid">
    

        <div class="pdf-data" style="margin: 30px">
                        <h5 class="card-header text-green">FORM NO.34 - Nomination</h5>

            <a id="data_to_image_btn" class="btn btn-info btn-nda-down"><i class="fa fa-download"></i>
                                Download</a>
             <div id="pdfExport">

         <div class="pdf-sipl">
              <div class="pdf-header-sipl"> <img src="../Logo/Sainmarknewlogo.png" width="130"
                    height="50" />


            
        <p><b>Sainmarks Industries (India) Pvt Ltd</b><br />
            476/1b/1a, Label Arcade, Jothi Nagar, Palavanjipalayam,<br />
            Dharapuram Main Road, Tirupur-641 608.</p>
    </div>
    <hr />


   






    <center> <h3>FORM NO.34 - Nomination<br />(விதி 93 C இன் கீழ் பரிந்துரைக்கப்பட்டது)</h3></center>

    <p>எனது இறப்பிற்கு பின்னால் கம்பெனியில் இருந்து எனக்கு சேர வேண்டிய சம்பளம் மற்றும்
        இதர படிகள் அனைத்தும் __________________________ எனது
        ______________________________ அவர்களுக்கு வழங்குமாறு கேட்டுக்கொள்கிறேன். மேலும்
        தற்போது அவர்கள் கீழ்க்கண்ட விலாசத்தில் வசித்து வருகிறார்கள்.</p>

    <p>முகவரி</p>
    <br /><br /><br /><br />






    <p>நன்றி</p>

    <br /><br />
    <p>தங்கள் உண்மையுள்ள</p>

    <br /><br />
    <p>தொழிலாளர் கையொப்பம்</p>

    <p>சாட்சி</p>
    <br /><br />
    <p>1</p>
    <br /><br />
    <p>2</p>



</div>









</div>


                        </div>



                    </div>


             

                 

              



                    <?php include '../footer.php'?>
                </div>




            </div>

            <?php include '../footerjs.php'?>
            <script src="../Scripts/jspdf.min.js"></script>

            <script src="../Scripts/html2canvas/html2canvas.min.js"></script>
            <!-- <script src="../Scripts/Controller/HRMtestcontroller.js"></script> -->
<script>


$(function() {
        $("#data_to_image_btn").click(function() {

            var HTML_Width = $("#pdfExport").width();
            var HTML_Height = $("#pdfExport").height();
            var data = document.getElementById('pdfExport');
            html2canvas(data, { allowTaint: true, scale: 3, useCORS: true, logging: true, }).then(canvas => {


                var contentWidth = canvas.width;
                var contentHeight = canvas.height;

                //One page pdf shows the canvas height generated by html pages.
                var pageHeight = contentWidth / 592.28 * 841.89;
                //html page height without pdf generation
                var leftHeight = contentHeight;
                //Page offset
                var position = 2;
                //a4 paper size [595.28, 841.89], html page generated canvas in pdf picture width
                var imgWidth = 595.28;
                var imgHeight = 592.28 / contentWidth * contentHeight;
                var pageData = canvas.toDataURL('image/jpeg', 1.0);
                var pdf = new jsPDF('', 'pt', 'a4');
                //There are two heights to distinguish, one is the actual height of the html page, and the page height of the generated pdf (841.89)
                //When the content does not exceed the range of pdf page display, there is no need to paginate
                if (leftHeight < pageHeight) {
                    pdf.addImage(pageData, 'JPEG', 2, 2, imgWidth, imgHeight);
                } else {
                    while (leftHeight > 0) {
                        pdf.addImage(pageData, 'JPEG', 2, position, imgWidth, imgHeight)
                        leftHeight -= pageHeight;
                        position -= 841.89;
                        //Avoid adding blank pages
                        if (leftHeight > 0) {
                            pdf.addPage();
                        }
                    }
                }
                // pdf.save('content.pdf');


                window.open(pdf.output('bloburl', {
                    filename: 'new-file.pdf'
                }), '_blank');
            });

        });
    });
</script>
           
</body>

</html>